### ISSUE TITLE
[BUG] Metadatum "Qualifikation" in "Rolle" umbenennen

### ISSUE THREAD

**Issue by gerhardglatz** [plusmeta/iirds-open-toolkit#38]
**Beschreibung**
Aktuell kann man das Metadatum "Qualifikation" vergeben, was dann intern auf iirds:Role gemappt wird. 
iirds:Qualification ist die Oberklasse von iirds:Role und iirds:SkillLevel und soll nicht direkt verwendet werden. 
Um dies auch für Anwender:innen deutlich zu machen, soll "Qualifikation" in "Rolle" umbenannt werden.

**Verwandte Probleme / Issues**
Bessere Anwenderunterstüzung.

**Betroffene Teile der Anwendung**
- Ansichten

**Comment by corneliusweikert** [comment]
Wenn man im OT unter dem Metadatum "Qualifikation" eigene Werte einträgt und die Metadaten speichert, wird im RDF die Oberklasse "Qualifikation" verwendet, nicht "iirds:Role". Wird das in diesem Issue ebenfalls behoben?
![image](https://github.com/plusmeta/iirds-open-toolkit/assets/109136213/92161ce8-71c0-4f4f-a923-f1ad02abd107)
